name: educa_jus_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - gradio
  - openai
  - langgraph
  - python-dotenv
  - pip
  - pip:
      - sentence-transformers>=2.7.0
      - faiss-cpu>=1.7.4
      - numpy>=1.26.0
